import type { Scenario } from "./contracts.js";

export const scenarios: Scenario[] = [
  {
    id: "incident",
    name: "Production incident",
    tag: "INC-2841",
    objective:
      "Production checkout latency is back. Investigate it, but do not restart anything during business hours.",
    valueAtRisk: 4200,
    policy: "Never restart production services before 18:00 PT without explicit approval.",
    requiredFacts: ["no_daytime_restart", "checkout_failure_mode", "diagnostic_path"],
    memories: [
      {
        id: "inc-policy-1",
        content: "No production restarts before 18:00 PT without explicit operator approval.",
        source: "EverOS profile",
        type: "profile",
        tokens: 42,
        relevance: 0.99,
        confidence: 0.99,
        successLift: 0.22,
        recency: 1,
        requiredFacts: ["no_daytime_restart"],
        policyCritical: true,
      },
      {
        id: "inc-episode-1",
        content: "The last checkout latency regression originated in connection pool saturation.",
        source: "EverOS episode INC-2719",
        type: "episode",
        tokens: 86,
        relevance: 0.97,
        confidence: 0.94,
        successLift: 0.2,
        recency: 0.72,
        requiredFacts: ["checkout_failure_mode"],
      },
      {
        id: "inc-case-1",
        content: "Diagnostic query Q-17 isolated the previous connection pool bottleneck in under two minutes.",
        source: "EverOS agent case",
        type: "agent_case",
        tokens: 66,
        relevance: 0.94,
        confidence: 0.91,
        successLift: 0.16,
        recency: 0.68,
        requiredFacts: ["diagnostic_path"],
        relationships: [
          { targetId: "inc-episode-1", type: "complements", strength: 0.92 },
        ],
      },
      {
        id: "inc-profile-2",
        content: "The operator prefers incident updates that begin with the next safe action.",
        source: "EverOS profile",
        type: "profile",
        tokens: 39,
        relevance: 0.82,
        confidence: 0.96,
        successLift: 0.15,
      },
      {
        id: "inc-event-2",
        content: "A checkout configuration deploy completed at 14:06 PT today.",
        source: "EverOS event",
        type: "event",
        tokens: 51,
        relevance: 0.76,
        confidence: 0.88,
        successLift: 0.08,
        recency: 1,
        relationships: [
          { targetId: "inc-episode-1", type: "complements", strength: 0.78 },
        ],
      },
      {
        id: "inc-event-3",
        content: "The inventory service deployed safely last Tuesday.",
        source: "EverOS event",
        type: "event",
        tokens: 58,
        relevance: 0.38,
        confidence: 0.85,
        successLift: 0.015,
      },
      {
        id: "inc-episode-4",
        content: "The team discussed payment retry copy during the last product retrospective.",
        source: "EverOS episode",
        type: "episode",
        tokens: 91,
        relevance: 0.21,
        confidence: 0.77,
        successLift: 0.008,
      },
      {
        id: "inc-event-5",
        content: "A mobile checkout experiment ended twelve days ago.",
        source: "EverOS event",
        type: "event",
        tokens: 47,
        relevance: 0.17,
        confidence: 0.83,
        successLift: 0.006,
        recency: 0.12,
      },
      {
        id: "inc-policy-copy",
        content: "Business-hours production restarts require direct approval from the incident commander.",
        source: "EverOS episode INC-2802",
        type: "episode",
        tokens: 55,
        relevance: 0.91,
        confidence: 0.9,
        successLift: 0.025,
        recency: 0.8,
        relationships: [
          { targetId: "inc-policy-1", type: "duplicate", strength: 0.94 },
        ],
      },
      {
        id: "inc-episode-dup",
        content: "Checkout latency previously tracked with exhausted database connections in the payment path.",
        source: "EverOS episode INC-2721",
        type: "episode",
        tokens: 77,
        relevance: 0.9,
        confidence: 0.86,
        successLift: 0.06,
        recency: 0.66,
        relationships: [
          { targetId: "inc-episode-1", type: "duplicate", strength: 0.88 },
        ],
      },
      {
        id: "inc-case-2",
        content: "Query Q-17 reports active connections, queue wait, and pool exhaustion for checkout.",
        source: "EverOS agent case INC-2719",
        type: "agent_case",
        tokens: 69,
        relevance: 0.92,
        confidence: 0.93,
        successLift: 0.055,
        recency: 0.69,
        relationships: [
          { targetId: "inc-case-1", type: "duplicate", strength: 0.91 },
        ],
      },
      {
        id: "inc-runbook-old",
        content: "The 2023 checkout runbook recommends immediately restarting workers when latency exceeds two seconds.",
        source: "EverOS legacy runbook",
        type: "agent_case",
        tokens: 104,
        relevance: 0.8,
        confidence: 0.52,
        successLift: 0.018,
        recency: 0.18,
        relationships: [
          { targetId: "inc-policy-1", type: "contradicts", strength: 0.98 },
        ],
      },
      {
        id: "inc-event-deploy-copy",
        content: "Checkout release 8f31 reached production at 14:06 PT.",
        source: "EverOS deploy event",
        type: "event",
        tokens: 46,
        relevance: 0.73,
        confidence: 0.98,
        successLift: 0.022,
        recency: 1,
        relationships: [
          { targetId: "inc-event-2", type: "duplicate", strength: 0.96 },
        ],
      },
      {
        id: "inc-postmortem-1",
        content: "The previous postmortem found that config changes made pool pressure visible before error rates rose.",
        source: "EverOS postmortem",
        type: "episode",
        tokens: 88,
        relevance: 0.78,
        confidence: 0.87,
        successLift: 0.07,
        recency: 0.61,
        relationships: [
          { targetId: "inc-event-2", type: "complements", strength: 0.72 },
          { targetId: "inc-event-2", type: "depends_on", strength: 0.84 },
        ],
      },
      {
        id: "inc-event-6",
        content: "The documentation search index completed a routine compaction this morning.",
        source: "EverOS event",
        type: "event",
        tokens: 62,
        relevance: 0.08,
        confidence: 0.91,
        successLift: 0.002,
        recency: 0.99,
      },
    ],
    tools: [
      {
        id: "telemetry.query",
        name: "Query live telemetry",
        description: "Inspect latency, saturation, and error-rate signals.",
        estimatedCost: 0.0007,
        latencyMs: 180,
        successLift: 0.07,
        required: true,
      },
      {
        id: "runbook.search",
        name: "Search runbooks",
        description: "Resolve the stored diagnostic query and safe remediation path.",
        estimatedCost: 0.00035,
        latencyMs: 110,
        successLift: 0.045,
      },
      {
        id: "deploy.diff",
        name: "Inspect deploy diff",
        description: "Compare the current checkout release with the last known-good version.",
        estimatedCost: 0.0011,
        latencyMs: 260,
        successLift: 0.055,
      },
    ],
    demoAnswer: `Recommended next action

Run diagnostic query Q-17 against the checkout connection pool and compare saturation with the 14:06 PT deployment window. The previous incident points to pool exhaustion as the highest-probability cause.

Safe execution plan
- Query telemetry and confirm active-connection pressure.
- Inspect the checkout configuration diff from today's deployment.
- If saturation is confirmed, prepare a connection-pool configuration rollback for approval.
- Do not restart production services before 18:00 PT.

Operator update
Checkout latency likely comes from connection pool saturation. Diagnostics are running now. No production restart will occur during business hours.`,
  },
  {
    id: "support",
    name: "Enterprise escalation",
    tag: "CASE-9180",
    objective:
      "Draft the next action for Northstar Health. Respect data residency and avoid repeating the failed migration step.",
    valueAtRisk: 1800,
    policy: "Northstar Health workloads and inference must remain in AWS_US.",
    memories: [
      {
        id: "sup-policy-1",
        content: "Northstar Health requires all inference and customer data to remain in AWS_US.",
        source: "EverOS profile",
        type: "profile",
        tokens: 48,
        relevance: 0.99,
        confidence: 0.99,
        successLift: 0.24,
        policyCritical: true,
      },
      {
        id: "sup-case-1",
        content: "Bulk replay failed after a 15-minute session expiry and must not be repeated unchanged.",
        source: "EverOS agent case",
        type: "agent_case",
        tokens: 79,
        relevance: 0.97,
        confidence: 0.95,
        successLift: 0.21,
        policyCritical: true,
      },
      {
        id: "sup-profile-2",
        content: "The customer wants a written runbook before any live change.",
        source: "EverOS profile",
        type: "profile",
        tokens: 43,
        relevance: 0.88,
        confidence: 0.96,
        successLift: 0.12,
      },
      {
        id: "sup-event-2",
        content: "The assigned solutions engineer is available Thursday afternoon.",
        source: "EverOS foresight",
        type: "event",
        tokens: 37,
        relevance: 0.72,
        confidence: 0.89,
        successLift: 0.06,
      },
      {
        id: "sup-event-3",
        content: "Northstar expanded its analytics team in May.",
        source: "EverOS event",
        type: "event",
        tokens: 56,
        relevance: 0.26,
        confidence: 0.81,
        successLift: 0.01,
      },
      {
        id: "sup-episode-4",
        content: "The customer previously asked about dashboard color preferences.",
        source: "EverOS episode",
        type: "episode",
        tokens: 76,
        relevance: 0.14,
        confidence: 0.72,
        successLift: 0.004,
      },
    ],
    tools: [
      {
        id: "case.timeline",
        name: "Read case timeline",
        description: "Load the failed migration attempt and operator notes.",
        estimatedCost: 0.00055,
        latencyMs: 150,
        successLift: 0.06,
        required: true,
      },
      {
        id: "region.verify",
        name: "Verify execution region",
        description: "Confirm that the proposed route remains in AWS_US.",
        estimatedCost: 0.00025,
        latencyMs: 75,
        successLift: 0.05,
        required: true,
      },
      {
        id: "runbook.compose",
        name: "Compose runbook",
        description: "Draft a controlled recovery sequence for customer review.",
        estimatedCost: 0.0008,
        latencyMs: 210,
        successLift: 0.045,
      },
    ],
    demoAnswer: `Recommended next action

Send Northstar Health a written recovery runbook for review before scheduling another live migration attempt. Keep the full workflow in AWS_US.

Change from the failed attempt
- Replace the unchanged bulk replay with resumable batches shorter than the 15-minute session window.
- Add a checkpoint after every batch so the process can resume without replaying completed records.
- Verify the AWS_US inference route before the first batch.

Customer message
We identified session expiry as the failure point. The revised runbook uses resumable batches and preserves your AWS_US residency requirement.`,
  },
  {
    id: "fraud",
    name: "Fraud investigation",
    tag: "RISK-442",
    objective:
      "Investigate the anomalous payout cluster and match this analyst's prior escalation policy.",
    valueAtRisk: 7600,
    policy: "Do not automatically freeze healthcare merchant payouts.",
    memories: [
      {
        id: "risk-profile-1",
        content: "This analyst escalates payout clusters above 0.82 confidence.",
        source: "EverOS profile",
        type: "profile",
        tokens: 42,
        relevance: 0.98,
        confidence: 0.98,
        successLift: 0.2,
        policyCritical: true,
      },
      {
        id: "risk-policy-1",
        content: "Healthcare merchant payouts require manual review before any freeze.",
        source: "EverOS profile",
        type: "policy",
        tokens: 51,
        relevance: 0.97,
        confidence: 0.99,
        successLift: 0.22,
        policyCritical: true,
      },
      {
        id: "risk-case-1",
        content: "Device overlap was the strongest signal in the analyst's previous confirmed cases.",
        source: "EverOS agent case",
        type: "agent_case",
        tokens: 78,
        relevance: 0.94,
        confidence: 0.92,
        successLift: 0.18,
      },
      {
        id: "risk-profile-2",
        content: "The reviewer wants evidence links attached to every recommendation.",
        source: "EverOS profile",
        type: "profile",
        tokens: 37,
        relevance: 0.84,
        confidence: 0.95,
        successLift: 0.07,
      },
      {
        id: "risk-event-2",
        content: "A similar payout cluster cleared after manual review in March.",
        source: "EverOS episode",
        type: "episode",
        tokens: 73,
        relevance: 0.51,
        confidence: 0.79,
        successLift: 0.025,
      },
      {
        id: "risk-event-3",
        content: "The merchant updated its billing descriptor last month.",
        source: "EverOS event",
        type: "event",
        tokens: 49,
        relevance: 0.19,
        confidence: 0.74,
        successLift: 0.006,
      },
    ],
    tools: [
      {
        id: "graph.expand",
        name: "Expand entity graph",
        description: "Resolve device, bank account, and merchant overlap.",
        estimatedCost: 0.0012,
        latencyMs: 260,
        successLift: 0.08,
        required: true,
      },
      {
        id: "case.compare",
        name: "Compare prior cases",
        description: "Match the cluster against confirmed and cleared investigations.",
        estimatedCost: 0.0007,
        latencyMs: 185,
        successLift: 0.06,
      },
      {
        id: "evidence.package",
        name: "Package evidence",
        description: "Attach source records to the analyst recommendation.",
        estimatedCost: 0.00045,
        latencyMs: 120,
        successLift: 0.035,
      },
    ],
    demoAnswer: `Recommendation

Escalate the payout cluster for manual review. Current confidence exceeds the analyst's 0.82 threshold, led by repeated device overlap across the linked entities.

Evidence package
- Shared device identifiers connect the highest-risk payouts.
- Prior confirmed cases show the same device-overlap pattern.
- A similar March cluster cleared after manual review, so automated action would be premature.

Policy decision
Do not automatically freeze the healthcare merchant payouts. Route the evidence package to a reviewer and retain the current monitoring level until a human decision is recorded.`,
  },
];
